import type { LegalContent } from './types';

export const privacyPolicy: LegalContent = {
  en: {
    title: 'Privacy Policy',
    lastUpdated: '2026-01-14',
    effectiveDate: '2026-01-14',
    sections: [
      {
        title: '1. Introduction',
        content: [
          'At PolitiTrades, we are committed to protecting your privacy and ensuring the security of your personal data. This Privacy Policy explains how we collect, use, store, and protect your information when you use our mobile application.',
          'We comply with the General Data Protection Regulation (GDPR) and other applicable data protection laws.',
          'The data controller for your personal information is [COMPANY NAME], located at [ADDRESS], SIRET: [SIRET].',
        ],
      },
      {
        title: '2. Data We Collect',
        content: [
          'We collect the following categories of personal data:',
          'Account Data:',
          '• Email address (required for account creation)',
          '• Name (if provided during sign-up)',
          '• Authentication tokens (managed by Supabase Auth)',
          '• Social sign-in data (if you choose to sign in with a social provider)',
          'Usage Data:',
          '• App interactions and feature usage',
          '• Search queries and filters applied',
          '• Alerts and notification preferences',
          '• Session duration and frequency of use',
          'Device Data:',
          '• Device type and model',
          '• Operating system and version',
          '• App version',
          '• Device identifiers (for analytics purposes)',
          'Push Notification Data:',
          '• Push notification tokens (to send you alerts)',
          'Subscription Data:',
          '• Subscription status and plan type (managed by RevenueCat)',
          '• Subscription start and renewal dates',
          '• Note: We do NOT collect or store payment information. All payments are processed directly by Apple App Store.',
        ],
      },
      {
        title: '3. How We Use Your Data',
        content: [
          'We process your personal data for the following purposes:',
          'Service Provision (Legal Basis: Contract Performance):',
          '• Create and manage your account',
          '• Authenticate your identity',
          '• Provide access to insider trading data',
          '• Deliver personalized alerts and notifications',
          'Communication (Legal Basis: Legitimate Interest):',
          '• Send service-related announcements',
          '• Respond to your support requests',
          '• Notify you of important updates to our Terms or Privacy Policy',
          'Improvement & Analytics (Legal Basis: Legitimate Interest):',
          '• Analyze app usage to improve user experience',
          '• Identify and fix bugs and technical issues',
          '• Develop new features and functionality',
          'Legal Compliance (Legal Basis: Legal Obligation):',
          '• Comply with applicable laws and regulations',
          '• Respond to legal requests and prevent fraud',
          'We do NOT use your data for:',
          '• Selling or renting to third parties',
          '• Targeted advertising or ad tracking',
          '• Automated decision-making or profiling',
        ],
      },
      {
        title: '4. Data Storage & Security',
        content: [
          'Your data is stored securely using Supabase, a trusted cloud infrastructure provider with servers located in [specify EU or US regions].',
          'Security measures we implement:',
          '• End-to-end encryption for data in transit (TLS/SSL)',
          '• Encryption at rest for all stored data',
          '• Row-level security (RLS) policies to ensure users can only access their own data',
          '• Regular security audits and vulnerability assessments',
          '• Strict access controls limiting employee access to personal data',
          'While we implement industry-standard security measures, no method of transmission or storage is 100% secure. We cannot guarantee absolute security of your data.',
        ],
      },
      {
        title: '5. Third-Party Services',
        content: [
          'We use the following third-party service providers who may process your personal data:',
          'Supabase (Database & Authentication):',
          '• Stores user account data, preferences, and alerts',
          '• Privacy Policy: https://supabase.com/privacy',
          'RevenueCat (Subscription Management):',
          '• Manages subscription status and entitlements',
          '• Privacy Policy: https://www.revenuecat.com/privacy',
          'Apple App Store (Payment Processing):',
          '• Processes all subscription payments',
          '• Privacy Policy: https://www.apple.com/legal/privacy/',
          'Each third-party provider processes data in accordance with their own privacy policies. We recommend reviewing these policies to understand how they handle your information.',
          'We only share the minimum data necessary for these providers to deliver their services.',
        ],
      },
      {
        title: '6. Data Retention',
        content: [
          'We retain your personal data for as long as necessary to provide our services and comply with legal obligations:',
          'Active Accounts:',
          '• Your data is retained for the duration of your active account',
          'Deleted Accounts:',
          '• Upon account deletion, your personal data will be permanently removed from our systems within 30 days',
          '• Some data may be retained longer if required by law (e.g., financial records for tax purposes)',
          'Anonymized Data:',
          '• We may retain anonymized usage data indefinitely for analytics and research purposes',
          '• This data cannot be used to identify you personally',
        ],
      },
      {
        title: '7. Your GDPR Rights',
        content: [
          'If you are located in the European Union, you have the following rights under GDPR:',
          'Right to Access:',
          '• Request a copy of the personal data we hold about you',
          'Right to Rectification:',
          '• Request correction of inaccurate or incomplete data',
          'Right to Erasure ("Right to be Forgotten"):',
          '• Request deletion of your personal data',
          '• Note: Certain data may be retained if required by law',
          'Right to Data Portability:',
          '• Receive your data in a structured, machine-readable format',
          '• Transfer your data to another service provider',
          'Right to Object:',
          '• Object to processing of your data for direct marketing purposes',
          '• Object to processing based on legitimate interests',
          'Right to Restrict Processing:',
          '• Request limitation of how we process your data under certain circumstances',
          'Right to Withdraw Consent:',
          '• Withdraw consent for data processing at any time (does not affect prior processing)',
          'To exercise any of these rights, please contact us at [EMAIL] or [DPO EMAIL]. We will respond to your request within 30 days.',
          'You also have the right to lodge a complaint with your local data protection authority if you believe we have violated your privacy rights.',
        ],
      },
      {
        title: '8. Cookies & Tracking',
        content: [
          'As a native mobile application, PolitiTrades does not use web cookies or browser-based tracking technologies.',
          'We may collect anonymized analytics data to understand app usage patterns, but this data is not linked to your personal identity.',
          'We do NOT use advertising identifiers (IDFA) or share data with advertising networks.',
        ],
      },
      {
        title: '9. International Data Transfers',
        content: [
          'Your data may be transferred to and processed in countries outside your country of residence, including the United States.',
          'When we transfer data internationally, we ensure appropriate safeguards are in place, such as:',
          '• Standard Contractual Clauses (SCCs) approved by the European Commission',
          '• Data Processing Agreements with our service providers',
          '• Adherence to frameworks like the EU-U.S. Data Privacy Framework (if applicable)',
          'By using our App, you consent to the transfer of your data to these jurisdictions.',
        ],
      },
      {
        title: '10. Children\'s Privacy',
        content: [
          'PolitiTrades is not intended for use by individuals under the age of 18 (or 16 in some EU countries).',
          'We do not knowingly collect personal data from minors. If we become aware that we have inadvertently collected data from a minor, we will take steps to delete it promptly.',
          'If you are a parent or guardian and believe your child has provided us with personal data, please contact us at [EMAIL].',
        ],
      },
      {
        title: '11. Changes to This Privacy Policy',
        content: [
          'We may update this Privacy Policy from time to time to reflect changes in our practices or legal requirements.',
          'If we make material changes, we will notify you by:',
          '• Sending an email to your registered email address',
          '• Displaying a prominent notice in the App',
          'The "Last Updated" date at the top of this policy indicates when it was last revised.',
          'We encourage you to review this Privacy Policy periodically to stay informed about how we protect your data.',
        ],
      },
      {
        title: '12. Contact Us',
        content: [
          'If you have any questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact us:',
          '[COMPANY NAME]',
          '[ADDRESS]',
          'Email: [EMAIL]',
          'Data Protection Officer: [DPO EMAIL]',
          'SIRET: [SIRET]',
          'We are committed to resolving any privacy concerns you may have.',
        ],
      },
    ],
  },
  fr: {
    title: 'Politique de Confidentialité',
    lastUpdated: '2026-01-14',
    effectiveDate: '2026-01-14',
    sections: [
      {
        title: '1. Introduction',
        content: [
          'Chez PolitiTrades, nous nous engageons à protéger votre vie privée et à garantir la sécurité de vos données personnelles. Cette Politique de Confidentialité explique comment nous collectons, utilisons, stockons et protégeons vos informations lorsque vous utilisez notre application mobile.',
          'Nous nous conformons au Règlement Général sur la Protection des Données (RGPD) et aux autres lois applicables en matière de protection des données.',
          'Le responsable du traitement de vos données personnelles est [COMPANY NAME], situé à [ADDRESS], SIRET : [SIRET].',
        ],
      },
      {
        title: '2. Données que Nous Collectons',
        content: [
          'Nous collectons les catégories suivantes de données personnelles :',
          'Données de Compte :',
          '• Adresse e-mail (requise pour la création de compte)',
          '• Nom (si fourni lors de l\'inscription)',
          '• Jetons d\'authentification (gérés par Supabase Auth)',
          '• Données de connexion sociale (si vous choisissez de vous connecter via un fournisseur social)',
          'Données d\'Utilisation :',
          '• Interactions avec l\'application et utilisation des fonctionnalités',
          '• Requêtes de recherche et filtres appliqués',
          '• Préférences d\'alertes et de notifications',
          '• Durée et fréquence d\'utilisation des sessions',
          'Données d\'Appareil :',
          '• Type et modèle d\'appareil',
          '• Système d\'exploitation et version',
          '• Version de l\'application',
          '• Identifiants d\'appareil (à des fins d\'analyse)',
          'Données de Notification Push :',
          '• Jetons de notification push (pour vous envoyer des alertes)',
          'Données d\'Abonnement :',
          '• Statut et type de plan d\'abonnement (géré par RevenueCat)',
          '• Dates de début et de renouvellement de l\'abonnement',
          '• Note : Nous NE collectons NI ne stockons d\'informations de paiement. Tous les paiements sont traités directement par l\'App Store d\'Apple.',
        ],
      },
      {
        title: '3. Comment Nous Utilisons Vos Données',
        content: [
          'Nous traitons vos données personnelles aux fins suivantes :',
          'Fourniture du Service (Base légale : Exécution du contrat) :',
          '• Créer et gérer votre compte',
          '• Authentifier votre identité',
          '• Fournir l\'accès aux données de transactions d\'initiés',
          '• Délivrer des alertes et notifications personnalisées',
          'Communication (Base légale : Intérêt légitime) :',
          '• Envoyer des annonces liées au service',
          '• Répondre à vos demandes de support',
          '• Vous informer des mises à jour importantes de nos Conditions ou de notre Politique de Confidentialité',
          'Amélioration et Analyses (Base légale : Intérêt légitime) :',
          '• Analyser l\'utilisation de l\'application pour améliorer l\'expérience utilisateur',
          '• Identifier et corriger les bugs et problèmes techniques',
          '• Développer de nouvelles fonctionnalités',
          'Conformité Légale (Base légale : Obligation légale) :',
          '• Se conformer aux lois et réglementations applicables',
          '• Répondre aux demandes légales et prévenir la fraude',
          'Nous N\'utilisons PAS vos données pour :',
          '• Vendre ou louer à des tiers',
          '• Publicité ciblée ou suivi publicitaire',
          '• Prise de décision automatisée ou profilage',
        ],
      },
      {
        title: '4. Stockage et Sécurité des Données',
        content: [
          'Vos données sont stockées de manière sécurisée en utilisant Supabase, un fournisseur d\'infrastructure cloud de confiance avec des serveurs situés dans [spécifier régions UE ou US].',
          'Mesures de sécurité que nous mettons en œuvre :',
          '• Chiffrement de bout en bout pour les données en transit (TLS/SSL)',
          '• Chiffrement au repos pour toutes les données stockées',
          '• Politiques de sécurité au niveau des lignes (RLS) pour garantir que les utilisateurs ne peuvent accéder qu\'à leurs propres données',
          '• Audits de sécurité réguliers et évaluations de vulnérabilité',
          '• Contrôles d\'accès stricts limitant l\'accès des employés aux données personnelles',
          'Bien que nous mettions en œuvre des mesures de sécurité standard de l\'industrie, aucune méthode de transmission ou de stockage n\'est sécurisée à 100%. Nous ne pouvons garantir la sécurité absolue de vos données.',
        ],
      },
      {
        title: '5. Services Tiers',
        content: [
          'Nous utilisons les fournisseurs de services tiers suivants qui peuvent traiter vos données personnelles :',
          'Supabase (Base de données et Authentification) :',
          '• Stocke les données de compte utilisateur, les préférences et les alertes',
          '• Politique de confidentialité : https://supabase.com/privacy',
          'RevenueCat (Gestion des Abonnements) :',
          '• Gère le statut et les droits d\'abonnement',
          '• Politique de confidentialité : https://www.revenuecat.com/privacy',
          'Apple App Store (Traitement des Paiements) :',
          '• Traite tous les paiements d\'abonnement',
          '• Politique de confidentialité : https://www.apple.com/legal/privacy/',
          'Chaque fournisseur tiers traite les données conformément à sa propre politique de confidentialité. Nous vous recommandons de consulter ces politiques pour comprendre comment ils gèrent vos informations.',
          'Nous ne partageons que le minimum de données nécessaires pour que ces fournisseurs puissent fournir leurs services.',
        ],
      },
      {
        title: '6. Conservation des Données',
        content: [
          'Nous conservons vos données personnelles aussi longtemps que nécessaire pour fournir nos services et nous conformer aux obligations légales :',
          'Comptes Actifs :',
          '• Vos données sont conservées pendant la durée de votre compte actif',
          'Comptes Supprimés :',
          '• Lors de la suppression du compte, vos données personnelles seront définitivement supprimées de nos systèmes dans un délai de 30 jours',
          '• Certaines données peuvent être conservées plus longtemps si la loi l\'exige (par exemple, les dossiers financiers à des fins fiscales)',
          'Données Anonymisées :',
          '• Nous pouvons conserver indéfiniment des données d\'utilisation anonymisées à des fins d\'analyse et de recherche',
          '• Ces données ne peuvent pas être utilisées pour vous identifier personnellement',
        ],
      },
      {
        title: '7. Vos Droits RGPD',
        content: [
          'Si vous êtes situé dans l\'Union Européenne, vous disposez des droits suivants en vertu du RGPD :',
          'Droit d\'Accès :',
          '• Demander une copie des données personnelles que nous détenons à votre sujet',
          'Droit de Rectification :',
          '• Demander la correction de données inexactes ou incomplètes',
          'Droit à l\'Effacement (« Droit à l\'Oubli ») :',
          '• Demander la suppression de vos données personnelles',
          '• Note : Certaines données peuvent être conservées si la loi l\'exige',
          'Droit à la Portabilité des Données :',
          '• Recevoir vos données dans un format structuré et lisible par machine',
          '• Transférer vos données à un autre fournisseur de services',
          'Droit d\'Opposition :',
          '• S\'opposer au traitement de vos données à des fins de marketing direct',
          '• S\'opposer au traitement fondé sur des intérêts légitimes',
          'Droit à la Limitation du Traitement :',
          '• Demander la limitation de la façon dont nous traitons vos données dans certaines circonstances',
          'Droit de Retirer le Consentement :',
          '• Retirer votre consentement pour le traitement des données à tout moment (n\'affecte pas le traitement antérieur)',
          'Pour exercer l\'un de ces droits, veuillez nous contacter à [EMAIL] ou [DPO EMAIL]. Nous répondrons à votre demande dans un délai de 30 jours.',
          'Vous avez également le droit de déposer une plainte auprès de votre autorité locale de protection des données si vous pensez que nous avons violé vos droits à la vie privée.',
        ],
      },
      {
        title: '8. Cookies et Suivi',
        content: [
          'En tant qu\'application mobile native, PolitiTrades n\'utilise pas de cookies web ou de technologies de suivi basées sur navigateur.',
          'Nous pouvons collecter des données d\'analyse anonymisées pour comprendre les modèles d\'utilisation de l\'application, mais ces données ne sont pas liées à votre identité personnelle.',
          'Nous N\'utilisons PAS d\'identifiants publicitaires (IDFA) ni ne partageons de données avec des réseaux publicitaires.',
        ],
      },
      {
        title: '9. Transferts Internationaux de Données',
        content: [
          'Vos données peuvent être transférées et traitées dans des pays en dehors de votre pays de résidence, y compris les États-Unis.',
          'Lorsque nous transférons des données au niveau international, nous nous assurons que des garanties appropriées sont en place, telles que :',
          '• Clauses contractuelles types (CCT) approuvées par la Commission européenne',
          '• Accords de traitement des données avec nos prestataires de services',
          '• Adhésion à des cadres comme le EU-U.S. Data Privacy Framework (le cas échéant)',
          'En utilisant notre Application, vous consentez au transfert de vos données vers ces juridictions.',
        ],
      },
      {
        title: '10. Confidentialité des Enfants',
        content: [
          'PolitiTrades n\'est pas destiné à être utilisé par des personnes de moins de 18 ans (ou 16 ans dans certains pays de l\'UE).',
          'Nous ne collectons pas sciemment de données personnelles auprès de mineurs. Si nous apprenons que nous avons collecté par inadvertance des données auprès d\'un mineur, nous prendrons des mesures pour les supprimer rapidement.',
          'Si vous êtes un parent ou un tuteur et pensez que votre enfant nous a fourni des données personnelles, veuillez nous contacter à [EMAIL].',
        ],
      },
      {
        title: '11. Modifications de cette Politique de Confidentialité',
        content: [
          'Nous pouvons mettre à jour cette Politique de Confidentialité de temps à autre pour refléter des changements dans nos pratiques ou des exigences légales.',
          'Si nous apportons des modifications importantes, nous vous en informerons en :',
          '• Envoyant un e-mail à votre adresse e-mail enregistrée',
          '• Affichant un avis visible dans l\'Application',
          'La date « Dernière mise à jour » en haut de cette politique indique quand elle a été révisée pour la dernière fois.',
          'Nous vous encourageons à consulter périodiquement cette Politique de Confidentialité pour rester informé de la façon dont nous protégeons vos données.',
        ],
      },
      {
        title: '12. Nous Contacter',
        content: [
          'Si vous avez des questions, préoccupations ou demandes concernant cette Politique de Confidentialité ou nos pratiques en matière de données, veuillez nous contacter :',
          '[COMPANY NAME]',
          '[ADDRESS]',
          'Email : [EMAIL]',
          'Délégué à la Protection des Données : [DPO EMAIL]',
          'SIRET : [SIRET]',
          'Nous nous engageons à résoudre toutes les préoccupations en matière de confidentialité que vous pourriez avoir.',
        ],
      },
    ],
  },
};
